-- MySQL Script generated by MySQL Workbench
-- Sat Oct 18 16:10:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `cli_Nome` VARCHAR(10) NULL DEFAULT NULL,
  `cli_NomeMeio` VARCHAR(10) NULL DEFAULT NULL,
  `cli_Sobrenome` VARCHAR(10) NULL DEFAULT NULL,
  `cli_CPF` CHAR(11) NOT NULL,
  `cli_End_Logradouro` VARCHAR(255) NULL DEFAULT NULL,
  `cli_End_Numero` INT NULL DEFAULT NULL,
  `cli_End_Complemento` VARCHAR(20) NULL DEFAULT NULL,
  `cli_End_Bairro` VARCHAR(30) NULL DEFAULT NULL,
  `cli_End_CEP` CHAR(8) NULL DEFAULT NULL,
  `cli_End_Cidade` VARCHAR(30) NULL DEFAULT NULL,
  `cli_End_Estado` ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NULL DEFAULT NULL,
  `cli_Nascimento` DATE NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_cpf_cliente` ON `clientes` (`cli_CPF` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estoqueprodutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueprodutos` (
  `idProdutoEstoque` INT NOT NULL AUTO_INCREMENT,
  `est_Localidade` VARCHAR(255) NULL DEFAULT NULL,
  `est_Quantidade` INT NULL DEFAULT '0',
  PRIMARY KEY (`idProdutoEstoque`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estoqueslocalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueslocalidades` (
  `idProdutoEstoque` INT NOT NULL,
  `idEstoque` INT NOT NULL,
  `est_Localidade` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idProdutoEstoque`, `idEstoque`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fornecedores` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `for_NomeSocial` VARCHAR(255) NOT NULL,
  `for_CNPJ` CHAR(15) NOT NULL,
  `for_ContatoTelefone` VARCHAR(11) NOT NULL,
  `for_Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_fornecedor` ON `fornecedores` (`for_CNPJ` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ordempedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordempedidos` (
  `idOrdemProduto` INT NOT NULL,
  `idOrdemPedido` INT NOT NULL,
  `ord_Quantidade` INT NULL DEFAULT '1',
  `ord_StatusPedido` ENUM('Disponível', 'Sem estoque') NULL DEFAULT 'Disponível',
  PRIMARY KEY (`idOrdemProduto`, `idOrdemPedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagamentos` (
  `idClientePagamento` INT NOT NULL,
  `idPagamento` INT NOT NULL,
  `pag_Tipo` ENUM('Boleto', 'Cartão Crédito') NULL DEFAULT NULL,
  `pag_LimiteLiberado` FLOAT NULL DEFAULT NULL,
  `pag_NumeroCartao` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idClientePagamento`, `idPagamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idPedidoCliente` INT NULL DEFAULT NULL,
  `ped_Status` ENUM('Cancelado', 'Confirmado', 'Em processamento', 'Enviado', 'Entregue') NULL DEFAULT 'Em processamento',
  `ped_Descricao` VARCHAR(255) NULL DEFAULT NULL,
  `ped_ValorEnvio` DECIMAL(10,2) NULL DEFAULT '10.00',
  `ped_Pagamento` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `prod_Nome` VARCHAR(255) NOT NULL,
  `prod_ClassificacaoKids` TINYINT(1) NULL DEFAULT '0',
  `prod_Categoria` ENUM('Eletrônico', 'Vestimenta', 'Brinquedos', 'Alimentos', 'Móveis') NOT NULL,
  `prod_Descricao` TEXT NULL DEFAULT NULL,
  `prod_Preco` DECIMAL(10,2) NOT NULL,
  `prod_Avaliacao` FLOAT NULL DEFAULT '0',
  `prod_Tamanho` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `produtosfornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtosfornecedores` (
  `idProdFor_Fornecedor` INT NOT NULL,
  `idProdFor_Produto` INT NOT NULL,
  `prodFor_Quantidade` INT NOT NULL,
  PRIMARY KEY (`idProdFor_Fornecedor`, `idProdFor_Produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `produtosvendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtosvendedores` (
  `idpVendedor` INT NOT NULL,
  `idpProduto` INT NOT NULL,
  `prodVend_Quantidade` INT NULL DEFAULT '1',
  PRIMARY KEY (`idpVendedor`, `idpProduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendedores` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `ven_nomeSocial` VARCHAR(255) NOT NULL,
  `ven_nomeAbstrato` VARCHAR(255) NULL DEFAULT NULL,
  `ven_CNPJ` CHAR(15) NULL DEFAULT NULL,
  `ven_CPF` CHAR(11) NULL DEFAULT NULL,
  `ven_localidade` VARCHAR(255) NULL DEFAULT NULL,
  `ven_contatoTelefone` CHAR(11) NOT NULL,
  `ven_Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idVendedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_cnpj_vendedores` ON `vendedores` (`ven_CNPJ` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_cpf_vendedores` ON `vendedores` (`ven_CPF` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
